# ansible task to: sudo dnf install dnf-plugins-core

- name: Install dnf-plugins-core
  dnf:
    name: dnf-plugins-core
    state: present

# ansible task: sudo dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo

- name: Add brave-browser repo
  yum_repository:
    name: brave-browser
    description: Brave Browser
    baseurl: https://brave-browser-rpm-release.s3.brave.com/x86_64/
    gpgkey: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    gpgcheck: yes
    enabled: yes

# ansible task: sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

- name: Import brave-browser GPG key
  rpm_key:
    key: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    state: present

# ansible task: sudo dnf install brave-browser brave-keyring

- name: Install brave-browser
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - brave-browser
    - brave-keyring