# ansible tasks to install docker

- name: Install docker
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

# ansible task to start docker service

- name: Start docker service
  service:
    name: docker
    state: started
    enabled: yes


# ansible task to add user to docker group

- name: Add user to docker group
  user:
    name: "{{ username }}"
    groups: docker
    append: yes
