# ansible task to update the system
- name: Update system
  dnf:
    name: '*'
    state: latest
    update_cache: yes

- name: Enabling the RPM Fusion repositories
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - "https://download0.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm"
    - "https://download0.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm"